name: Merge main into deprecate-ember-polaris

on:
  push:
    branches:
      - main

jobs:
  merge_into_deprecate_ember_polaris:
    name: Smile CI merge main into deprecate-ember-polaris.
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Merge ${{ github.ref }} into deprecate-ember-polaris"
        id: merge
        uses: devmasx/merge-branch@854d3ac71ed1e9deb668e0074781b81fdd6e771f # 1.4.0
        with:
          type: now
          from_branch: ${{ github.ref }}
          target_branch: deprecate-ember-polaris
          github_token: ${{ secrets.GITHUB_TOKEN }}
